_BASE_: "../Base-FCOS.yaml"
MODEL:
  # WEIGHTS: "pretrained_models/vovnet/vovnet57_ese_detectron2.pth"
  WEIGHTS: "pretrained_models/FCOS_vovnet/FCOS_V57_MS_3x_gu.pth"
  # "https://www.dropbox.com/s/8xl0cb3jj51f45a/vovnet57_ese_detectron2.pth?dl=1"
  BACKBONE:
    NAME: "build_fcos_vovnet_fpn_backbone"
    FREEZE_AT: 0 # 0
  VOVNET:
    CONV_BODY : "V-57-eSE"
    OUT_FEATURES: ["stage3", "stage4", "stage5"]
  FPN:
    IN_FEATURES: ["stage3", "stage4", "stage5"]
  FCOS:
    NUM_CLASSES: 30

SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.001

  REL_STEPS: (0.78, 0.926)
  TOTAL_EPOCHS: 8

DATASETS:
  TRAIN: ("tless_pbr_train", "tless_train_primesense_fuse_coco")
  TEST: ("tless_bop_test_primesense",)

INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  # MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
  COLOR_AUG_ON: True
  COLOR_AUG_TYPE: "CODE"
  COLOR_AUG_CODE: |
    Sequential([
      Sometimes(0.4, CoarseDropout( p=0.1, size_percent=0.05) ),
      # Sometimes(0.5, Affine(scale=(1.0, 1.2))),
      Sometimes(0.5, GaussianBlur(np.random.rand())),
      Sometimes(0.5, Add((-20, 20), per_channel=0.3)),
      Sometimes(0.4, Invert(0.20, per_channel=True)),
      Sometimes(0.5, Multiply((0.7, 1.4), per_channel=0.8)),
      Sometimes(0.5, Multiply((0.7, 1.4))),
      Sometimes(0.5, ContrastNormalization((0.5, 2.0), per_channel=0.3))],
      random_order=False)
    # aae weaker

OUTPUT_DIR: "output/bop_det/tless/fcos_V57eSE_MSx1333_ColorAugAAEWeaker_8e_tless_real_pbr"
